---

# handlers for partner-codes permissions
- name: nginx permissions to partner-codes assets
  file:
    path: "{{ item }}"
    owner: www-data
    group: www-data
    mode: 0755
    state: directory
    recurse: yes

  with_items:
    - "{{ partner_codes_www_root }}"
    - "{{ partner_codes_www_static_dir }}"

# Handlers for Nginx notifications.

- name: stop nginx
  systemd:
    name: nginx
    state: stopped

- name: start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    masked: no
    daemon_reload: yes

# Handlers for Mysql notifications.

- name: stop mysql
  systemd:
    name: mysql
    state: stopped

- name: start mysql
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: restart mysql
  systemd:
    name: mysql
    state: restarted
    enabled: yes
    masked: no
    daemon_reload: yes

# handlers for the gunicorn server

- name: stop partner-codes-app
  systemd:
    name: partner-codes-app
    state: stopped

- name: start partner-codes-app
  systemd:
    name: partner-codes-app
    state: started
    enabled: yes

- name: restart partner-codes-app
  systemd:
    name: partner-codes-app
    state: restarted
    enabled: yes
    masked: no
    daemon_reload: yes


- name: stop butterfly
  systemd:
    name: butterfly
    state: stopped

- name: start butterfly
  systemd:
    name: butterfly
    state: started
    enabled: yes

- name: restart butterfly
  systemd:
    name: butterfly
    state: restarted
    enabled: yes
    masked: no
    daemon_reload: yes

- name: stop gitea
  systemd:
    name: gitea.service
    state: stopped

- name: start gitea
  systemd:
    name: gitea.service
    state: started
    enabled: yes

- name: restart gitea
  systemd:
    name: gitea.service
    state: restarted
    enabled: yes
    masked: no
    daemon_reload: yes

- name: stop redis
  systemd:
    name: redis
    state: stopped

- name: start redis
  systemd:
    name: redis
    state: started
    enabled: yes

- name: restart redis
  systemd:
    name: redis
    state: restarted
    enabled: yes
    masked: no
    daemon_reload: yes

- name: migrate partner-codes database
  shell: "{{ partner_codes_venv_dir }}/bin/alembic upgrade head"
  args:
    chdir: "{{ partner_codes_src_dir }}"
