logging:
  level: DEBUG

caching:
  timeout: 30
  high_water_mark: 500
  directory: /partner-codes/databases

dao:
  s3:
    bucket_name: partner-codes
    namespace: dao

  file_system:
    storage_path: /partner-codes/databases

app:
  BASE_URL: 'https://partner.codes'

  STATE_STORAGE_PATH:

  SWAGGER_UI_DOC_EXPANSION: list
  SWAGGER_UI_JSONEDITOR: yes
  RESTPLUS_VALIDATE: yes

  FORCE_SCHEMA_VALIDATION: no

  TIMEZONE: 'America/New_York'
  DATETIME_LOCALE: 'us'

aws:
  create_missing_config: no
  s3:
    default_bucket_name: partner-codes

  profile:
    partner_codes:
      output: "json"
      region: "ams3"

  credentials:
    partner_codes:
      aws_access_key_id: VVGZI33HH5HHDUKCHP77
      aws_secret_access_key: Jr3b2xAOycbnrgkM7R44bHY2jj/dmv6tGMHwNJyraZE

boto3:
  session_config:
    aws_access_key_id: VVGZI33HH5HHDUKCHP77
    aws_secret_access_key: Jr3b2xAOycbnrgkM7R44bHY2jj/dmv6tGMHwNJyraZE
    region_name: "nyc3"
    profile_name: "partner-codes"
    endpoint_url: https://nyc3.digitaloceanspaces.com
